[versions]
kotlin = "2.1.21"
androidx-compose-ui-test = "1.8.3"

[libraries]
android-plugin = 'com.android.tools.build:gradle:8.10.1'

androidx-activity-compose = "androidx.activity:activity-compose:1.10.1"
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "androidx-compose-ui-test" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-ui-test" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

jetbrains-compose-gradlePlugin = "org.jetbrains.compose:compose-gradle-plugin:1.9.0-alpha02"

binary-compatibility-validator-gradlePlugin = "org.jetbrains.kotlinx:binary-compatibility-validator:0.17.0"
cklib-gradlePlugin = "co.touchlab:cklib-gradle-plugin:0.3.4"
jextract-gradlePlugin = "de.infolektuell:gradle-plugin-jextract:0.5.0"

spotless-gradlePlugin = "com.diffplug.spotless:spotless-plugin-gradle:7.0.4"
ktlint-core = "com.pinterest.ktlint:ktlint-cli:1.6.0"
ktlint-composeRules = "io.nlopez.compose.rules:ktlint:0.4.22"

junit4 = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
